### ISSUE TITLE
HTML tags in body

### ISSUE THREAD

**Issue by kp77** [RippleAdder/Modus-Javascript-Bridge#6]
Is it possible to use HTML in the body text? I'd like to use links, but in iOS the HTML code is displayed in the message.

**Comment by kp77** [comment]
In the example index.html there are examples of functions like `sendHTMLMail` and `sendHTMLMailEncoded`, but these don't seem to work and I couldn't find them in the js code.

**Comment by RippleAdder** [comment]
Yes HTML is possible, but the email body must begin with an html open tag (<), then the iOS app detects that the body is HTML and sets the MFMailComposeViewController to expect HTML in the body.  sendHTMLMail and sendHTMLMailEncoded both use the JS bridge's sendEmail method under the hood, you can see this in index.html line 20 for example.  I will take a peek and see if these are working locally.  What client are you working with?

**Comment by kp77** [comment]
Hi RippleAdder,

Thanks for the quick response. I tried what you suggested and it kind of works. I added the html tag, and now the email app interprets the link as html (it display it as a link in the message text). However, the email that I received stripped out the link, I only got the text but it was not linked.

I used the `sendEmailEncoded` method for this. When I tried to use the `sendHTMLMail` method nothing happened (the email app didn't start).

Not sure about the client question, I'm trying this on an iPad with iOS10, if that's what you mean.

**Comment by RippleAdder** [comment]
Hmm that is interesting.  What is the email address you are sending to?  I mean, what type of email is it?  Gmail?  It almost sounds like the incoming email is being stripped.  

I just meant if to ask if you are working with one of our clients (customers) on a piece of content.

**Comment by kp77** [comment]
I've sent  it to Gmail, which usually doesnt't have issues. Yes, I need to transfer an app for a client using ADR. Anyway, huge thanks for the help, I'm going to look into it a bit more tomorrow, but now at least I know it's possible.
